---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: thanos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-destroyer
subjects:
  - kind: ServiceAccount
    name: thanos
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-destroyer
rules:
- apiGroups: [""]
  resources: ['pods']
  verbs:     ['*']
